- hosts: all
  become: true
  vars:
    repo_url: "https://github.com/kitsanaphon1/ansible-var.git"
    repo_branch: "dev"

  tasks:
    - name: "🧹 ลบโฟลเดอร์เดิมออก (ถ้ามี)"
      file:
        path: /home/azureuser/app
        state: absent

    - name: "📁 สร้างโฟลเดอร์ app สำหรับ clone"
      file:
        path: /home/azureuser/app
        state: directory
        mode: '0755'

    - name: "📥 Clone Git repository ลง VM"
      git:
        repo: "{{ repo_url }}"
        dest: /home/azureuser/app
        version: "{{ repo_branch }}"
        force: yes

    - name: "🐳 Build Docker image: Api"
      shell: docker build -t webapi:latest /home/azureuser/app/docker/Api

    - name: "🐳 Build Docker image: WebAppProject"
      shell: docker build -t webapp:latest /home/azureuser/app/docker/WebAppProject
